// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfavdtiinbzgqhfczkps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmYXZkdGlpbmJ6Z3FoZmN6a3BzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNzA1MzQsImV4cCI6MjA2ODc0NjUzNH0.X1EOld9xVmm7RnfJxJu3D84xmbqQdOLklfG_EqEJhkc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});